# logFilters:
#   - code: YN0061
#     level: discard
#   - code: YN0032
#     level: discard

# nodeLinker: node-modules

# packageExtensions:
#   "@vue/babel-plugin-jsx@^1.0.0-0":
#     dependencies:
#       "@babel/core": ^7.11.0
#   "@vue/cli-plugin-unit-mocha@~4.5.0":
#     dependencies:
#       webpack: ^4.0.0
#   "@vue/cli-service@~4.5.0":
#     dependencies:
#       vue-loader: ^15.9.6
#     peerDependencies:
#       "@vue/cli-plugin-babel": ~4.5.0
#       "@vue/cli-plugin-eslint": ~4.5.0
#       "@vue/cli-plugin-pwa": ~4.5.0
#       "@vue/cli-plugin-router": ~4.5.0
#       "@vue/cli-plugin-unit-mocha": ~4.5.0
#   babel-loader@*:
#     dependencies:
#       "@babel/core": "*"
#   sass-loader@^8.0.2:
#     peerDependencies:
#       webpack: ^4.36.0
#   vue-router@*:
#     peerDependencies:
#       vue: "*"
#   vue-template-compiler@*:
#     dependencies:
#       vue: "*"

yarnPath: .yarn/releases/yarn-1.23.0-20210103.1434.cjs
